Atualizado CI (1)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,31 +10,34 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Go
-      uses: actions/setup-go@v2
-      with:
-        go-version: 1.20
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Install dependencies
-      run: |
-        go mod download
-        go mod tidy
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: 1.20
+          cache-dependency-path: '**/go.sum'
 
-    - name: Run tests
-      run: |
-        failed_tests=$(go list ./... | xargs -n1 go test -coverprofile=coverage.out 2>&1 | grep -E "(FAIL|no test files)" || echo "")
-        if [ -n "$failed_tests" ]; then
-          echo "Existem pacotes com falhas ou sem testes:"
-          echo "$failed_tests"
-          exit 1
-        fi
+      - name: Install dependencies
+        run: |
+          go mod download
+          go mod tidy
 
-    - name: Check test coverage
-      run: |
-        threshold=98.0
-        coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
-        if (( $(echo "$coverage < $threshold" | bc -l) )); then
-          echo "Test coverage is below the threshold of $threshold%"
-          exit 1
-        fi
+      - name: Run tests
+        run: |
+          failed_tests=$(go list ./... | xargs -n1 go test -coverprofile=coverage.out 2>&1 | grep -E "(FAIL|no test files)" || echo "")
+          if [ -n "$failed_tests" ]; then
+            echo "Existem pacotes com falhas ou sem testes:"
+            echo "$failed_tests"
+            exit 1
+          fi
+
+      - name: Check test coverage
+        run: |
+          threshold=98.0
+          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
+          if (( $(echo "$coverage < $threshold" | bc -l) )); then
+            echo "Test coverage is below the threshold of $threshold%"
+            exit 1
+          fi
