Atualizado ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,13 @@ jobs:
         go mod tidy
 
     - name: Run tests
-      run: go test -coverprofile=coverage.out ./...
+      run: |
+        failed_tests=$(go list ./... | xargs -n1 go test -coverprofile=coverage.out 2>&1 | grep -E "(FAIL|no test files)" || echo "")
+        if [ -n "$failed_tests" ]; then
+          echo "Existem pacotes com falhas ou sem testes:"
+          echo "$failed_tests"
+          exit 1
+        fi
 
     - name: Check test coverage
       run: |
